### ISSUE TITLE
Header parsing and decoder

### ISSUE THREAD

**Issue by dnigh** [gregjhogan/rwd-xray#1]
The decode algorithm doesn't work for 5A rwds, it needs to be e = ((( i + k1 ) - k2 ) ^ k3 ) & 0xFF.
Also 5A parsing trips up on the two 4 byte addresses after the key, It sees the first 2 0x00 of the first address and back steps once thus starting the decode 1 byte early on SH7058 calibrations and is even more off on SH7254 calibrations. A fix I found that worked was replacing "if null_cnt == 2" with "if idx == 6". Comments in the code ask about what the addresses represent, the first is the address at which to start the flash procedure, the second is the length of the calibration flash. I think the last 4 bytes might be a checksum for the Honda software but I haven't found supporting evidence yet

**Comment by gregjhogan** [comment]
@dnigh why do you think it is `(((i + k1 ) - k2 ) ^ k3) & 0xFF`?  When I use the same cipher that the 31 format uses for the calibration file named `36802TLA_A050M1__A1705341.rwd.gz` I see text in the .bin file output that is very close to part numbers (e.g. `;6802-TLA-A050` @ 0x542), but when I use what you suggested I don't find anything similar. Thanks!

**Comment by dnigh** [comment]
Hmmm...I think the cipher changes depending on the type of module to be
programmed. The cipher I posted works for 5A 37805 files which are for
ECUs. I'll try it with some 31 37805 files this evening. There's some
interest in this on RomRaider's Honda Development forum if you're looking
for more collaboration

**Comment by dnigh** [comment]
Something I noticed when working on the 5A 37805 cipher before getting to
the one I posted was that sometimes it got close but not all the bytes
transformed correctly. I'd get some bytes that were correct and some that
were off when comparing against a raw dump, that may be what's happening
with the TLA calibration. How'd you come up with the 31 cipher if I may ask?

**Comment by gregjhogan** [comment]
I updated the code to brute force the cipher and output a file for any set of operators that result in the part number showing up in the decrypted firmware.  That seems to narrow it down to one or two options.

**Comment by gregjhogan** [comment]
I think this is resolved, let me know if it isn't
