### ISSUE TITLE
first 1800 bytes are zeros

### ISSUE THREAD

**Issue by adamPrune** [gregjhogan/rwd-xray#2]
Thanks for sharing your work. I tried extracting a binary from 39990-TV9-A910.rwd and the first 1800 bytes are all zeros. Is it the same for you? I think there might be something wrong with my .rwd or the way I extract the binary :-/

**Comment by gregjhogan** [comment]
That is correct.  The [format of the firmware for that rwd file](https://github.com/gregjhogan/rwd-xray#firmware-1) that splits the firmware up into 128 byte blocks, and each block has an address associated with it.  The first address in that file is 0x1800 and whenever there is a gap in the addresses I fill the gaps with zero.

**Comment by gregjhogan** [comment]
closing until someone suggests something better

**Comment by gregjhogan** [comment]
re-opened because it seems like I should write out a separate .bin file for each contiguous memory block

**Comment by gregjhogan** [comment]
I updated the code to put the start address in the file name and not pad with \x00 up to the start address (so you will no longer see \x00 in the first 0x1800 bytes).  I found there are often lots of address blocks with small jumps, so it seems like it makes sense to keep it as a single output .bin file.
