### ISSUE TITLE
Decryption failed!

### ISSUE THREAD

**Issue by EcuDrugWash** [gregjhogan/rwd-xray#4]
Hello,

I need  you help with decryption of rwd file.
Whe I try to use you program with my file I got the message:
.............................................................................................................................................
decryption failed!
(could not find a cipher that results in the part number being in the data)

**Comment by gregjhogan** [comment]
what is the name of the file you ran through it?  currently there is an assumption that the part number will show up as text somewhere in the firmware.  maybe we can find something else to search for if that is the issue

**Comment by gregjhogan** [comment]
Try passing a smaller substring of the part number into the decryption:
https://github.com/gregjhogan/rwd-xray/blob/c094c5abfb3c7382b32a2b4f8452907fb3d58770/rwd-xray.py#L52

**Comment by gregjhogan** [comment]
What did you try changing `part_number_prefix` to?

**Comment by EcuDrugWash** [comment]
# part_number_prefix = 'RBB-J530'  - doesn't work
    # part_number_prefix = 'RBB-J530-M2' - doesn't work 
    # part_number_prefix = '37805-RBB-J530' - doesn't work

**Comment by gregjhogan** [comment]
Try the beginning of the part number `37805`

**Comment by EcuDrugWash** [comment]
Ok.

**Comment by twizzter** [comment]
Try 3377880550 instead of 37805, in some dumps ID string occurs in weird, kinda-interleaved way.

**Comment by twizzter** [comment]
> thanks @twizzter so how do I translate a part number into that format? 

 I've analysed few dumps and i believe i found some dependency:

Let's assume filename is ABCDE-FGH-IJKL, then ID inside would be something like:
AABBCCDEED--FFG[always C]H[always A]--I[always A]J[always 0]KL[always 00]

Second thing: if filename in named like smth-smth-smth_H710_H720_H730, only last H730 is taken and coded inside dump.

Don't know if this "algo" will work with files other than 37805 (ECUs). 
Anyway, we could simply look for "3377880550" for now.

**Comment by gregjhogan** [comment]
Looks like it is the part number with an extra character after each character in the part number.  I added this as a second way to search for the part number when decrypting and it works now on this file.  Pull latest to try it out.

Thanks for the help solving this!  Hopefully this adds support for a number of files that previously failed.
